version: "3.2"
services:
  backoffice-front:
    restart: always
    command : yarn start
    container_name: aishortsmaker-backoffice-front
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      PORT: ${SERVER_PORT}
    stdin_open: true